### ISSUE TITLE
Cell Ontology (CL) search page does not load from Ontologies page

### ISSUE THREAD

**Issue by ghost** [EBISPOT/ols4#308]
The following was observed in the Safari browser.

**Expected**: Clicking on CL from the [Ontologies search page](https://www.ebi.ac.uk/ols4/ontologies) would lead to the CL search page. This functions as expected in OLS3.
![OLS3-CL-search-page](https://user-images.githubusercontent.com/95643797/231456471-e32b1109-e6d7-47a6-9896-e40fa716272f.gif)

--

**Observed**: In OLS4, when searching for CL on the [Ontologies search page](https://www.ebi.ac.uk/ols4/ontologies), it is first noted that the CL logo does not load. Secondly, clicking on the link leads to a blank screen. Clicking to navigate back to previous pages does not seem to function.
![OLS4-CL-search-page](https://user-images.githubusercontent.com/95643797/231458314-ad4d43ba-08c3-4809-b836-d962016c4663.gif)

**Proposed fix**: 1. Fix link to the CL ontology search page. 2. Add CL logo/icon.

**Comment by jamesamcl** [comment]
Thanks Bradley - this is fixed now.

**Comment by ghost** [comment]
Thank you, @udp. The CL ontology link in OLS4 now works, however the CL logo still does not load.
