### ISSUE TITLE
SEMAPV: some issues with display

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/ols4#420]
## Hierarchy does not work

If you try to expand the hierarchy, nothing shows up

<img width="603" alt="image" src="https://github.com/EBISPOT/ols4/assets/7070631/94a30d00-b889-4097-9b5a-b93036d828df">

Same for properties: https://www.ebi.ac.uk/ols4/ontologies/semapv/properties/http%253A%252F%252Fwww.w3.org%252F2004%252F02%252Fskos%252Fcore%2523mappingRelation?lang=en

## Label with skos:prefLabel

semapv_Mapping label -> should be "mapping", based on `skos:prefLabel` 

<img width="555" alt="image" src="https://github.com/EBISPOT/ols4/assets/7070631/be6ab535-21d7-451a-bda2-74c16499c0b4">

**Comment by henrietteharmse** [comment]
Change made. Waiting for functional dev environment.

**Comment by henrietteharmse** [comment]
Done

**Comment by matentzn** [comment]
Seems this is still not picked up:

https://github.com/EBISPOT/ols4/blob/dev/ebi_ontologies.json#L10

The labels are not rendered at all!

**Comment by henrietteharmse** [comment]
![image](https://github.com/EBISPOT/ols4/assets/32327979/69a9670b-9970-4ce4-bbd3-43688bbbac38)

**Comment by matentzn** [comment]
Looks fantastic! Thank you!
